# Generated by Django 4.1.3 on 2023-05-27 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.day')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status')),
                ('timetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timetable')),
            ],
        ),
    ]
