# Generated by Django 4.1.3 on 2023-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_code',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='days',
            field=models.ManyToManyField(to='app.day'),
        ),
    ]
